version: "3.8"
services:
  gateway:
    env_file:
      - compose.env
    build:
      context: .
      dockerfile: docker/gateway-gpu.dockerfile
      args:
        - BASE_VERSION=weibo-base:0.0.0-gpu
    image: weibo-filter-gateway:0.0.0-gpu
    ports:
      - ${PORT}:9004
    depends_on:
      - base
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${GATEWAY_CPUS}
  base:
    build:
      context: ./docker
      dockerfile: base-gpu.dockerfile
    image: weibo-base:0.0.0-gpu
    deploy:
      replicas: 0
